Factory/Models/Engineer.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Factory.Models
{
  public class Engineer
  {
    public int EngineerId { get; set; }

    // We didn't learn this but I was able to find a solution by myself. We learnt about empty fields but not invalid values.
    // Prompt - I should not be able to create an engineer or a machine if the form's fields are empty or contain INVALID VALUES.
    [Required]
    [RegularExpression("^[a-zA-Z][a-zA-Z0-9]*$", ErrorMessage = "The engineer's name can't be empty and it can only be alphabetic!")]
    public string Name { get; set; }

    [Required]
    [RegularExpression("Beginner|Intermediate|Expert", ErrorMessage = "Please provide an experience level, it can be one of the three level ('Beginner', 'Intermediate', 'Expert').")]
    public string Experience { get; set; }

    public List<Repair> JoinEntities { get; } // collection navigation property.
  }
}

Factory/Controllers/EngineersController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;
using Factory.Models;

namespace Factory.Controllers
{
  public class EngineersController : Controller
  {
    private readonly FactoryContext _db;

    public EngineersController(FactoryContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Engineer> model = _db.Engineers.ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Engineer engineer)
    {
      if (!ModelState.IsValid)
      {
        return View();
      }
      else
      {
        _db.Engineers.Add(engineer);
        _db.SaveChanges();
        return RedirectToAction("Index");
      }
    }

    public ActionResult Details(int id)
    {
      Engineer thisEngineer = _db.Engineers
          .Include(engineer => engineer.JoinEntities)
          .ThenInclude(join => join.Machine)
          .FirstOrDefault(engineer => engineer.EngineerId == id);
      return View(thisEngineer);
    }

    public ActionResult Edit(int id)
    {
      Engineer thisEngineer = _db.Engineers.FirstOrDefault(engineer => engineer.EngineerId == id);
      return View(thisEngineer);
    }

    [HttpPost]
    public ActionResult Edit(Engineer engineer)
    {
      if (!ModelState.IsValid)
      {
        return View();
      }
      else
      {
        _db.Engineers.Update(engineer);
        _db.SaveChanges();
        return RedirectToAction("Index");
      }
    }

    public ActionResult Delete(int id)
    {
      Engineer thisEngineer = _db.Engineers.FirstOrDefault(engineer => engineer.EngineerId == id);
      return View(thisEngineer);
    }


    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Engineer thisEngineer = _db.Engineers.FirstOrDefault(engineer => engineer.EngineerId == id);
      _db.Engineers.Remove(thisEngineer);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult AddMachine(int id)
    {
      Engineer thisEngineer = _db.Engineers.FirstOrDefault(engineer => engineer.EngineerId == id);
      ViewBag.MachineId = new SelectList(_db.Machines, "MachineId", "Name");
      return View(thisEngineer);
    }

    [HttpPost]
    public ActionResult AddMachine(Engineer engineer, int machineId)
    {
#nullable enable
      Repair? joinEntity = _db.Repairs.FirstOrDefault(join => (join.MachineId == machineId && join.EngineerId == engineer.EngineerId));
#nullable disable
      if (joinEntity == null && machineId != 0)
      {
        _db.Repairs.Add(new Repair() { MachineId = machineId, EngineerId = engineer.EngineerId });
        _db.SaveChanges();
      }
      return RedirectToAction("Details", new { id = engineer.EngineerId });
    }

    [HttpPost]
    public ActionResult DeleteJoin(int joinId)
    {
      Repair joinEntry = _db.Repairs.FirstOrDefault(entry => entry.RepairId == joinId);
      _db.Repairs.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

  }
}

Factory/Views/Engineers/AddMachine.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Engineer

<h2>Add a Machine</h2>
<hr/>

<h4>Assign a machine to this engineer: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.EngineerId)

    @Html.Label("Select Machine")
    @Html.DropDownList("MachineId")

    <input type="submit" value="Save" />
}

<p>@Html.ActionLink("Back to Engineer List", "Index")</p>

Factory/Views/Engineers/Create.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Engineer

<h4>Add a New Engineer</h4>

<p>@Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger", @style = "font-weight: 600;" })</p>
<p>@Html.ValidationMessageFor(model => model.Experience, "", new { @class = "text-danger", @style = "font-weight: 600;" })</p>

@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Name)
  @Html.TextBoxFor(model => model.Name)

  @Html.LabelFor(model => model.Experience)
  @Html.TextBoxFor(model => model.Experience)

  <input type="submit" value="Add New Engineer" class="btn btn-primary" />
}
<p>@Html.ActionLink("Show All Engineers", "Index")</p>

Factory/Views/Engineers/Delete.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Engineer

<h2>Are you sure you want to delete this engineer?</h2>

@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)

@using (Html.BeginForm())
{
    <input type="submit" value="Delete" />
}

@Html.ActionLink("Back to Engineer List", "Index")

Factory/Views/Engineers/Details.cshtml
@{
  Layout = "_Layout";
}

@using Factory.Models
@model Factory.Models.Engineer

<h2>Engineer Details</h2>
<hr />
<h3>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)</h3>
<h3>@Html.DisplayNameFor(model => model.Experience): @Html.DisplayFor(model => model.Experience)</h3>

@if(@Model.JoinEntities.Count == 0)
{
  <p>This engineer is not assigned to repair any machine yet.</p>
}
else
{
  <h4>This engineer has been assigned to repair the following machines:</h4>
  <ul>
    @foreach(Repair join in Model.JoinEntities)
    {
      <li>Machine: @join.Machine.Name</li>
      @using (Html.BeginForm("DeleteJoin", "Engineers"))
      {
        @Html.Hidden("joinId", @join.RepairId)
        <input type="submit" value="Delete"/>
      }
    }
  </ul>
}


<p>@Html.ActionLink("Back to Engineer List", "Index")</p>
<p>@Html.ActionLink("Edit Engineer", "Edit", new { id = Model.EngineerId })</p>
<p>@Html.ActionLink("Assign Repair to Engineer", "AddMachine", new { id = Model.EngineerId })</p>
<p>@Html.ActionLink("Delete Engineer", "Delete", new { id = Model.EngineerId })</p>

Factory/Views/Engineers/Edit.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Engineer

<h2>Edit Engineer</h2>
<hr/>

<p>@Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger", @style = "font-weight: 600;" })</p>
<p>@Html.ValidationMessageFor(model => model.Experience, "", new { @class = "text-danger", @style = "font-weight: 600;" })</p>

<h4>Edit this engineer: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.EngineerId)

  @Html.LabelFor(model => model.Name)
  @Html.EditorFor(model => model.Name)

  @Html.LabelFor(model => model.Experience)
  @Html.EditorFor(model => model.Experience)


  <input type="submit" value="Save" />
}

<p>@Html.ActionLink("Back to Engineer List", "Index")</p>

Factory/Views/Engineers/Index.cshtml
@{
  Layout = "_Layout";
}

@using Factory.Models;


<h1>Engineers</h1>
<hr/>

@if (@Model.Count == 0)
{
  <h3>No engineers have been added yet!</h3>
} 
else
{
  <ul>
    @foreach (Engineer engineer in Model)
    {
      <li>@Html.ActionLink($"{engineer.Name}", "Details", new { id = engineer.EngineerId })</li>
    }
  </ul>
}

<p>@Html.ActionLink("Home", "Index", "Home")</p>
<p>@Html.ActionLink("Add New Engineer", "Create")</p>